services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - .:/app              # map your source code
      - /app/node_modules       # avoid overwriting node_modules inside container
    ports:
      - "19000:19000"   # Metro bundler
      - "19001:19001"   # iOS
      - "19002:19002"   # Web devtools (if enabled)
      - "8081:8081"     # Metro fallback
      - "19006:19006"   # Expo web
    env_file:
      - .env.development 
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=host.docker.internal
    stdin_open: true
    tty: true


  supabase-db:
    image: supabase/postgres:15.1.0.68
   # restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: supabase_pass
      POSTGRES_USER: supabase_user
      POSTGRES_DB: supabase_db
    volumes:
      - supabase-data:/var/lib/postgresql/data

  supabase-auth:
    image: supabase/gotrue:v2.153.0
  #  restart: always
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_user:supabase_pass@supabase-db:5432/supabase_db
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: super-secret-jwt-token
      API_EXTERNAL_URL: http://localhost:9999
    ports:
      - "9999:9999"
    depends_on:
      - supabase-db


  supabase-api:
    image: postgrest/postgrest:v12.0.1   
  #  restart: always
    environment:
      PGRST_DB_URI: postgres://supabase_user:supabase_pass@supabase-db:5432/supabase_db
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: super-secret-jwt-token
    ports:
      - "3000:3000"
    depends_on:
      - supabase-db

  supabase-studio:
    image: supabase/studio:latest
  #  restart: always
    ports:
      - "54323:3000"
    environment:
      STUDIO_PG_META_URL: http://supabase-api:3000
    depends_on:
      - supabase-api

volumes:
  supabase-data:
